// Buchdatenbank
let books = [
  {
    id: 1,
    title: "The Productivity Project",
    author: "Chris Bailey",
    publisher: "Penguin Books",
    price: 17.99,
    category: "Productivität",
    summary:
      "Chris Bailey testet ein Jahr lang die besten Produktivitätsmethoden und liefert praktische Tipps für mehr Fokus und Effizienz.",
    likes: 42,
    liked: false,
    comments: [],
  },
  {
    id: 2,
    title: "Das einzige Buch, das Du über Finanzen lesen solltest",
    author: "Thomas Kehl",
    publisher: "Finanzfluss Verlag",
    price: 19.99,
    category: "Finanzen",
    summary:
      "Einsteigerfreundlicher Ratgeber zu Geldanlage, ETFs und Sparplänen – verständlich und praxisnah erklärt.",
    likes: 67,
    liked: false,
    comments: [],
  },
  {
    id: 3,
    title: "The PARA Method",
    author: "Tiago Forte",
    publisher: "Forte Labs Press",
    price: 15.99,
    category: "Produktivität",
    summary:
      "Das PARA-System hilft, digitale Informationen zu organisieren und Klarheit im Arbeitsalltag zu schaffen.",
    likes: 89,
    liked: false,
    comments: [],
  },
  {
    id: 4,
    title: "Building a Second Brain",
    author: "Tiago Forte",
    publisher: "Forte Labs Press",
    price: 21.99,
    category: "Produktivität",
    summary:
      "Ein Leitfaden, wie man ein digitales Notizsystem aufbaut, um Wissen zu speichern und kreativ zu nutzen.",
    likes: 34,
    liked: false,
    comments: [],
  },
  {
    id: 5,
    title: "Die 7 Wege zur Effektivität",
    author: "Stephen R. Covey",
    publisher: "GABAL Verlag",
    price: 24.9,
    category: "Persönlichkeitsentwicklung",
    summary:
      "Covey beschreibt sieben Prinzipien, die zu mehr Erfolg und Zufriedenheit im Leben führen.",
    likes: 156,
    liked: false,
    comments: [],
  },
  {
    id: 6,
    title: "Die 1%-Methode (Atomic Habits)",
    author: "James Clear",
    publisher: "Goldmann Verlag",
    price: 16.99,
    category: "Gewohnheiten",
    summary:
      "Kleine Veränderungen führen zu großen Ergebnissen – ein praktischer Ansatz für nachhaltige Gewohnheiten.",
    likes: 198,
    liked: false,
    comments: [],
  },
  {
    id: 7,
    title: "Harry Potter und der Stein der Weisen",
    author: "J.K. Rowling",
    publisher: "Carlsen Verlag",
    price: 14.99,
    category: "Fantasy",
    summary:
      "Harry entdeckt die magische Welt von Hogwarts und stellt sich dem dunklen Magier Voldemort.",
    likes: 198,
    liked: false,
    comments: [],
  },
{
    id: 8,
    title: "Old Shatterhand",
    author: "Karl May",
    publisher: "Karl May Verlag",
    price: 13.99,
    category: "Abenteuer",
    summary:
      "Die Abenteuer von Old Shatterhand und Winnetou im Wilden Westen – Freundschaft, Mut und Gerechtigkeit.",
    likes: 198,
    liked: false,
    comments: [],
  }
];
